---
- name: Create app container
  docker_container:
    name: "{{application_name}}"
    image: "namelivia/{{application_name}}:0.0.4"
    restart_policy: "always"
    memory: "50MB"
    log_driver: "awslogs"
    log_options:
        awslogs-region: "{{cloudwatch_region}}"
        awslogs-group: "{{cloudwatch_log_group}}"
        awslogs-stream: "{{application_name}}"
    env:
      CONSUMER_KEY: "{{ consumer_key }}"
      CONSUMER_SECRET: "{{ consumer_secret }}"
      ACCESS_TOKEN_KEY: "{{ access_token_key }}"
      ACCESS_TOKEN_SECRET: "{{ access_token_secret }}"
      SEARCH_STRING: "{{ search_string }}"
      CHANCE_TO_ACT: "{{ chance_to_act }}"
      CHANCE_TO_FAVORITE: "{{ chance_to_favorite }}"
      CHANCE_TO_FOLLOW: "{{ chance_to_follow }}"
      LANGUAGE: "{{ language }}"
      IDLE_PERIOD: "{{ idle_period }}"
